apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: {{ .Release.Namespace }}
  labels:
    opendatahub.io/dashboard: 'true'
data:
  DEFAULT_BUCKET: mlflow-bucket
  DEFAULT_REGION: us-east-1
  BUCKET_PORT: 9000
